"""create table and admin user

Revision ID: ccd1b73ea246
Revises: 
Create Date: 2022-08-19 08:02:07.208468

"""
from alembic import op
import sqlalchemy as sa
from app.my_test_app.database.models import admin_user


# revision identifiers, used by Alembic.
revision = 'ccd1b73ea246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('login')
    )
    op.create_table('user_privileges',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('privileges', sa.String(), nullable=False),
    sa.Column('block', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['login'], ['users.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login')
    )

    # Добавляем пользователя 'admin' во время миграции

    meta = sa.MetaData(bind=op.get_bind())
    meta.reflect(only=("users", "user_privileges",))
    users = sa.Table("users", meta)
    user_privileges = sa.Table("user_privileges", meta)
    op.bulk_insert(users, [admin_user])
    op.bulk_insert(user_privileges, [admin_user])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_privileges')
    op.drop_table('users')
    # ### end Alembic commands ###
