"""create tables

Revision ID: da95d0c5ac43
Revises: 
Create Date: 2022-08-14 18:48:46.125871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da95d0c5ac43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('login')
    )
    op.create_table('user_privileges',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('privilege', sa.String(), nullable=False),
    sa.Column('block', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['login'], ['users.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_privileges')
    op.drop_table('users')
    # ### end Alembic commands ###
