common:
  port: 8080 # порт, на котором будет запускаться наше приложение
postgres:
  database_url: postgresql+asyncpg://testuser:password@localhost/testdb
  require_ssl: false # стоит ли шифровать соединение с базой